### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft3-typogrify#28] opened 2019-04-17 10:53 UTC
Hey Andrew,
Getting an unexpected output using PHP 7.3. I suspect this is an issue with an underlying library.

**Template**

```twig
{{ 'Adipiscing Vehicula Ridiculus Pharetra'|typogrify }}
```

**PHP 7.2 Output**

```html
Adipiscing Vehicula Ridiculus&nbsp;Pharetra
```

**PHP 7.3 Output**

```html
A&nbsp;d&nbsp;i&nbsp;p&nbsp;i&nbsp;s&nbsp;c&nbsp;i&nbsp;n&nbsp;g&nbsp;V&nbsp;e&nbsp;h&nbsp;i&nbsp;c&nbsp;u&nbsp;l&nbsp;a&nbsp;R&nbsp;i&nbsp;d&nbsp;i&nbsp;c&nbsp;u&nbsp;l&nbsp;u&nbsp;s&nbsp;P&nbsp;h&nbsp;a&nbsp;r&nbsp;e&nbsp;t&nbsp;r&nbsp;a&nbsp;
```

**Comment by khalwat** [comment] 2019-04-30 21:26
So this is going to be an issue with the underlying library, perhaps file an issue here ->

https://github.com/mundschenk-at/php-typography

**Comment by joshuabaker** [comment] 2019-05-03 10:50
I’ve just tested that library in isolation (same local server) without encountering the issue on PHP 7.3.

```php
<?php

require_once '../vendor/autoload.php';

$settings = new \PHP_Typography\Settings();
$settings->set_hyphenation(false);
$settings->set_max_dewidow_length(10);
$settings->set_max_dewidow_pull(10);

$typography = new \PHP_Typography\PHP_Typography();

echo $typography->process('Adipiscing Vehicula Ridiculus Pharetra', $settings);
```

Is there anything happening under the hood that might cause this?

**Comment by khalwat** [comment] 2019-05-03 14:46
hmmm the only differences I can think of is that here:

https://github.com/nystudio107/craft-typogrify/blob/v1/src/variables/TypogrifyVariable.php#L42

I do:

```php
Typogrify::$plugin->typogrify->typogrify($text, $isTitle);
```

Rather than `->process`

Also check the versions of the lib you're using directly vs. the version of the lib that Typogrify uses?

**Comment by joshuabaker** [comment] 2019-05-03 14:51
Thanks for reopening.

I’ve just checked in and the PHP Typography call is here: [TypogrifyService.php#L89](https://github.com/nystudio107/craft-typogrify/blob/ca3df19a42d74fd6e3e523edf330b98eb032ae60/src/services/TypogrifyService.php#L89)

```php
$result = $this->phpTypography->process($text, $this->phpTypographySettings, $isTitle);
```

**Comment by khalwat** [comment] 2019-05-03 14:53
Ah yes, sorry.

Yeah I can't think of anything I could be doing other than the `Template::raw()` which would then render raw if there were any HTML entities returned.

Also the fact that it works fine on all versions of PHP up to 7.3 have me thinking it could be a bit more involved.

**Comment by joshuabaker** [comment] 2019-05-03 14:58
Just to confirm, my test is using the same vendor directory.

Also, the `Template::raw()` call isn’t to blame here.

```php
echo Typogrify::$plugin->typogrify->typogrify('Adipiscing Vehicula Ridiculus Pharetra', false);
// Output: A&nbsp;d&nbsp;i&nbsp;p&nbsp;i&nbsp;s&nbsp;c&nbsp;i&nbsp;n&nbsp;g&nbsp;V&nbsp;e&nbsp;h&nbsp;i&nbsp;c&nbsp;u&nbsp;l&nbsp;a&nbsp;R&nbsp;i&nbsp;d&nbsp;i&nbsp;c&nbsp;u&nbsp;l&nbsp;u&nbsp;s&nbsp;P&nbsp;h&nbsp;a&nbsp;r&nbsp;e&nbsp;t&nbsp;r&nbsp;a&nbsp;
```

**Comment by joshuabaker** [comment] 2019-05-03 15:07
Andrew, sorry, I need to retract [my earlier comment](https://github.com/nystudio107/craft-typogrify/issues/28#issuecomment-489057240). The issue _is_ with the underlying library.

If having an open issue isn’t bothersome for you, please can we leave this open for now.

**Comment by khalwat** [comment] 2019-05-03 15:07
You got it.

**Comment by joshuabaker** [comment] 2019-05-03 15:12
mundschenk-at/php-typography#109

**Comment by mundschenk-at** [comment] 2019-05-05 06:27
@khalwat , have you been able to reproduce this issue? All the tests run fine on Travis with PHP 7.3.

**Comment by joshuabaker** [comment] 2019-05-07 19:18
@khalwat Is this happening for you too?

**Comment by khalwat** [comment] 2019-05-07 19:19
I'm not using PHP 7.3, so I haven't tried reproducing it yet; but I have heard of other people switching to PHP 7.3 and running into exactly this issue with both my plugin, and also the Wordsmith plugin (which both rely on your awesome library @mundschenk-at ).

**Comment by joshuabaker** [comment] 2019-05-07 19:22
Thanks, Andrew. 👍

I think there’s something happening along the way in Craft/Yii that’s impacting how that library works.

**Comment by khalwat** [comment] 2019-05-13 17:30
Looks like a Craft CMS issue, fixed in https://github.com/craftcms/cms/commit/8bf818a2e61a3468ab4630e45a9ad9ad42503975

**Closed as completed by khalwat** 2019-05-13 17:30 UTC
