### ISSUE TITLE
The "raw" and "typogrify" filters don't work together

### ISSUE THREAD

**Issue by jasonmorehead** [nystudio107/craft3-typogrify#17] opened 2018-10-08 15:08 UTC
There are times when I add simple HTML tags (like the `<em>` tag) to an entry title, or in a plain text field. When I just use the "typogrify" filter -- `{{ entry.title|typogrify }}` -- this is what the output looks like:

![screen shot 2018-10-08 at 10 01 37 am](https://user-images.githubusercontent.com/1703762/46616908-2a3ea100-cae1-11e8-9273-9721cf2993a8.png)

Which makes sense, based on the documentation. If I use the "raw" filter -- `{{ entry.title|raw }}` -- this is the output:

![screen shot 2018-10-08 at 10 02 41 am](https://user-images.githubusercontent.com/1703762/46616986-4fcbaa80-cae1-11e8-97d4-ac9ede13d1c7.png)

The `<em>` tag is rendered, but that quote is still a straight quote. Based on the documentation, I should be able to use the "raw" and "typogrify" filters together to get the desired effect (i.e., curly quotes and rendered HTML). But if I use `{{ entry.title|raw|typogrify }}`, this is the output:

![screen shot 2018-10-08 at 10 05 08 am](https://user-images.githubusercontent.com/1703762/46617146-a802ac80-cae1-11e8-9438-26b5c7aabadc.png)

It looks like the "raw" filter is completely ignored and only the "typogrify" filter is used.

I'm using Craft v3.0.26.1 and Typogrify v1.1.14.

**Comment by davidhellmann** [comment] 2018-10-08 16:05
Same here? Broken in the newest version?

**Comment by romainpoirier** [comment] 2018-10-09 07:40
Same here. And since version 1.1.13, I sometimes get this kind of error when `typogrify` filter is used in combination with another filter (like `t`, `replace`, `raw`, etc.):
`Call to undefined method nystudio107\typogrify\twigextensions\TypogrifyTwigExtension::typogrify() errors `

**Comment by khalwat** [comment] 2018-10-09 20:43
So @jasonmorehead in your example you have this:

```twig
{{ entry.title|raw }}
```

Did you mean this?
```twig
{{ entry.title | raw | typogrify }}
```

?

**Comment by khalwat** [comment] 2018-10-09 20:53
@davidhellmann I can't reproduce what you're talking about with `Call to undefined method ` -- can you please give me a code example?

**Comment by khalwat** [comment] 2018-10-09 20:53
@romainpoirier I can't reproduce what you're talking about with Call to undefined method -- can you please give me a code example?

**Comment by khalwat** [comment] 2018-10-09 20:54
Okay so @davidhellmann @jasonmorehead looks like you're right -- the assumption was that `| raw` would wrap the string in `\Twig_Markup`, but it does not. I'll have a look at how to address this.

**Comment by khalwat** [comment] 2018-10-09 21:08
Fixed in 1.1.15: https://github.com/nystudio107/craft-typogrify/releases/tag/1.1.15

**Closed as completed by khalwat** 2018-10-09 21:08 UTC

**Comment by davidhellmann** [comment] 2018-10-09 21:31
Thanks! :)

**Comment by romainpoirier** [comment] 2018-10-10 08:15
@khalwat, I've just update to 1.1.15 and can't reproduce these issues anymore :) Thank you!
